version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groupmate-backend
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/projectsync
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    container_name: groupmate-mongo
    ports:
    - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: